# This is a node.js v8+ JavaScript project
language: node_js
node_js:
  - "8"
go:
  - "1.9.1"

# Build on Ubuntu Trusty (14.04)
# https://docs.travis-ci.com/user/reference/trusty/#javascript-and-nodejs-images
dist: trusty
sudo: required

# Use Docker
services:
  - docker

before_install:
#  - ./test/setup/setup_script
  - docker pull openbazaar/server:v0.11.1
  - docker run --rm -v $(pwd)/test/obdata:/var/lib/openbazaar openbazaar/server:v0.11.1 init -d /var/lib/openbazaar
  - cp test/setup/config test/obdata/
  - docker-compose up
